version: "3"

services:
  omeka-s-red:
    image: omeka-s-red:1.2.0-0.3
    restart: always
    environment:
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_NAME: $DB_NAME
      DB_HOST: $DB_HOST
      DB_BACKUP: $DB_BACKUP
      SITE_BACKUP: $SITE_BACKUP
    ports:
      - $HOST_PORT:80
