version: "3"

services:
  omeka-s:
    build: .
    restart: always
    environment:
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_NAME: $DB_NAME
      DB_HOST: $DB_HOST
      DB_BACKUP: $DB_BACKUP
      SITE_BACKUP: $SITE_BACKUP
    ports:
      - 80:80
