version: "3"

services:
  # omeka-s-example:
  #   volumes:
  #     - ./files:/var/www/html/files

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PORT: 3306
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka
      MYSQL_DATABASE: omeka
    volumes:
      - omeka-s-mysql-data:/var/lib/mysql

volumes:
  omeka-s-mysql-data:
