version: "3"

services:
  omeka-s-mellon:
    image: omeka-s-mellon:1.3.0-0.1.1
    restart: always
    environment:
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_NAME: $DB_NAME
      DB_HOST: $DB_HOST
      DB_BACKUP: $DB_BACKUP
      SITE_BACKUP: $SITE_BACKUP
    ports:
      - $HOST_PORT:80
