version: "3"

services:
  omeka-s-mellon:
    image: omeka-s-mellon:latest
    restart: always
    environment:
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_NAME: $DB_NAME
      DB_HOST: $DB_HOST
      DB_BACKUP: $DB_BACKUP
      SITE_BACKUP: $SITE_BACKUP
    ports:
      - $HOST_PORT:80

  db:
    image: mariadb:10.4-bionic
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
    volumes:
      - $DB_LOCATION:/var/lib/mysql
